name: Code Check

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  code-check:
    name: â¬£ ESLint, Ê¦ TypeScript, and ðŸ’… Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: âŽ” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Code Check
        run: pnpm run check-all
